### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "abde enff kafka test",
  "email": "test07@test.kafka",
  "address": "123 qwe16 street",
  "dateOfBirth": "1994-09-09",
  "registeredDate": "1995-09-07"
}
###